"""Export research data to a branded PDF report using fpdf2."""
import logging
from datetime import date
from pathlib import Path

from fpdf import FPDF

logger = logging.getLogger(__name__)

# Verlumen brand colors
_NAVY = (74, 68, 67)       # #4A4443
_ACCENT = (160, 137, 104)  # #A08968
_WHITE = (255, 255, 255)
_LIGHT_GRAY = (245, 245, 245)
_GRAY = (128, 128, 128)
_GREEN = (200, 235, 210)
_YELLOW = (255, 243, 205)
_RED = (255, 210, 210)
_DARK = (50, 50, 50)


class VerlumenPDFReport(FPDF):
    """Custom FPDF subclass with Verlumen branding."""

    def header(self):
        if self.page_no() == 1:
            return  # Cover page has its own header
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*_NAVY)
        self.cell(0, 8, "Verlumen Market Research Report", align="L")
        self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*_ACCENT)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*_GRAY)
        self.cell(0, 10, "Generated by Verlumen Market Research Tool", align="C")


def export_pdf(products_data: list[dict], output_path: str) -> str:
    """Generate a branded PDF report.

    Parameters
    ----------
    products_data : list[dict]
        Same format as ExcelExporter.export(). Each item has: name, category,
        analysis, competitors, optionally ml_data and profit_data.
    output_path : str
        Destination file path for the .pdf file.

    Returns
    -------
    str  The absolute path of the created file.
    """
    pdf = VerlumenPDFReport(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)

    _build_cover_page(pdf, products_data)
    _build_product_summary_table(pdf, products_data)
    _build_product_detail_pages(pdf, products_data)

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    pdf.output(output_path)
    logger.info("PDF exported to %s", output_path)
    return str(Path(output_path).resolve())


# ---------------------------------------------------------------------------
# Page builders
# ---------------------------------------------------------------------------

def _build_cover_page(pdf: VerlumenPDFReport, products: list[dict]) -> None:
    """Page 1: Cover with executive summary KPIs."""
    pdf.add_page()

    # Title block
    pdf.ln(30)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*_NAVY)
    pdf.cell(0, 14, "Verlumen", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 20)
    pdf.set_text_color(*_ACCENT)
    pdf.cell(0, 12, "Market Research Report", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(*_GRAY)
    pdf.cell(
        0, 8,
        f"Generated: {date.today().strftime('%B %d, %Y')}",
        align="C", new_x="LMARGIN", new_y="NEXT",
    )

    # Divider
    pdf.ln(10)
    pdf.set_draw_color(*_ACCENT)
    pdf.set_line_width(0.8)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(15)

    # KPI calculations
    researched = [
        p for p in products
        if p.get("analysis") and p["analysis"].get("total_competitors", 0) > 0
    ]
    total_products = len(products)
    avg_opp = 0.0
    avg_comp = 0.0
    total_competitors = 0
    if researched:
        opp_scores = [p["analysis"].get("opportunity_score", 0) for p in researched]
        comp_scores = [p["analysis"].get("competition_score", 0) for p in researched]
        avg_opp = sum(opp_scores) / len(opp_scores)
        avg_comp = sum(comp_scores) / len(comp_scores)
        total_competitors = sum(
            p["analysis"].get("total_competitors", 0) for p in researched
        )

    # KPI summary heading
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_NAVY)
    pdf.cell(0, 10, "Executive Summary", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # KPI table
    kpis = [
        ("Total Products", str(total_products)),
        ("Avg Opportunity Score", f"{avg_opp:.1f}"),
        ("Avg Competition Score", f"{avg_comp:.1f}"),
        ("Total Competitors Tracked", str(total_competitors)),
    ]

    col_w = 85
    table_x = (210 - col_w * 2) / 2  # center the table

    # Header row
    pdf.set_x(table_x)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(*_NAVY)
    pdf.set_text_color(*_WHITE)
    pdf.cell(col_w, 9, "Metric", border=1, align="C", fill=True)
    pdf.cell(col_w, 9, "Value", border=1, align="C", fill=True, new_x="LMARGIN", new_y="NEXT")

    # Data rows
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_DARK)
    for i, (label, value) in enumerate(kpis):
        pdf.set_x(table_x)
        if i % 2 == 0:
            pdf.set_fill_color(*_LIGHT_GRAY)
        else:
            pdf.set_fill_color(*_WHITE)
        pdf.cell(col_w, 8, label, border=1, align="L", fill=True)
        pdf.cell(col_w, 8, value, border=1, align="C", fill=True, new_x="LMARGIN", new_y="NEXT")


def _build_product_summary_table(pdf: VerlumenPDFReport, products: list[dict]) -> None:
    """Product summary table with color-coded VVS scores."""
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_NAVY)
    pdf.cell(0, 10, "Product Summary", align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    headers = [
        "Product Name",
        "Category",
        "Status",
        "Compet.",
        "Avg Price",
        "Avg Rating",
        "Opp. Score",
        "VVS",
    ]
    col_widths = [48, 25, 20, 16, 20, 18, 20, 16]
    # total = 183 (fits in 190mm usable width)

    # Header row
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_NAVY)
    pdf.set_text_color(*_WHITE)
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 7, h, border=1, align="C", fill=True)
    pdf.ln()

    # Data rows
    pdf.set_font("Helvetica", "", 7)
    for row_idx, p in enumerate(products):
        a = p.get("analysis") or {}
        is_researched = bool(a and a.get("total_competitors", 0) > 0)

        num_competitors = a.get("total_competitors", 0) if is_researched else 0
        avg_price = f"${a.get('price_mean', 0):.2f}" if is_researched else "-"
        avg_rating = f"{a.get('avg_rating', 0):.1f}" if is_researched else "-"
        opp_score = f"{a.get('opportunity_score', 0):.1f}" if is_researched else "-"

        # VVS score (may be in ml_data or analysis)
        vvs_data = p.get("vvs_data") or {}
        vvs_score = vvs_data.get("vvs_score")
        vvs_str = f"{vvs_score:.1f}" if vvs_score is not None else "-"

        # Determine row fill color based on VVS score
        if vvs_score is not None and vvs_score >= 7:
            pdf.set_fill_color(*_GREEN)
        elif vvs_score is not None and vvs_score >= 4:
            pdf.set_fill_color(*_YELLOW)
        elif vvs_score is not None:
            pdf.set_fill_color(*_RED)
        elif row_idx % 2 == 0:
            pdf.set_fill_color(*_LIGHT_GRAY)
        else:
            pdf.set_fill_color(*_WHITE)

        pdf.set_text_color(*_DARK)

        status = "Researched" if is_researched else "Imported"
        name = p.get("name", "")
        # Truncate long names
        if len(name) > 28:
            name = name[:26] + ".."

        category = p.get("category", "")
        if len(category) > 14:
            category = category[:12] + ".."

        vals = [
            name,
            category,
            status,
            str(num_competitors),
            avg_price,
            avg_rating,
            opp_score,
            vvs_str,
        ]
        for i, v in enumerate(vals):
            align = "L" if i == 0 else "C"
            pdf.cell(col_widths[i], 6, v, border=1, align=align, fill=True)
        pdf.ln()

        # Check for page break
        if pdf.get_y() > 265:
            pdf.add_page()
            # Re-draw header
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_fill_color(*_NAVY)
            pdf.set_text_color(*_WHITE)
            for i, h in enumerate(headers):
                pdf.cell(col_widths[i], 7, h, border=1, align="C", fill=True)
            pdf.ln()
            pdf.set_font("Helvetica", "", 7)


def _build_product_detail_pages(pdf: VerlumenPDFReport, products: list[dict]) -> None:
    """Per-product detail pages with top 5 competitors."""
    for p in products:
        a = p.get("analysis") or {}
        competitors = p.get("competitors") or []
        is_researched = bool(a and a.get("total_competitors", 0) > 0)

        if not is_researched:
            continue  # Skip unresearched products

        pdf.add_page()

        # Product title
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(*_NAVY)
        pdf.cell(0, 10, _safe_text(p.get("name", "Unknown")), align="L", new_x="LMARGIN", new_y="NEXT")

        # Category
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*_ACCENT)
        pdf.cell(0, 6, f"Category: {p.get('category', 'Uncategorized')}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        # Quick stats
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_DARK)
        stats = [
            f"Competitors: {a.get('total_competitors', 0)}",
            f"Avg Price: ${a.get('price_mean', 0):.2f}",
            f"Avg Rating: {a.get('avg_rating', 0):.1f}",
            f"Opportunity Score: {a.get('opportunity_score', 0):.1f}",
            f"Competition Score: {a.get('competition_score', 0):.1f}",
        ]
        pdf.cell(0, 6, "  |  ".join(stats), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        # VVS verdict
        vvs_data = p.get("vvs_data") or {}
        if vvs_data.get("vvs_score") is not None:
            verdict = vvs_data.get("verdict", "N/A")
            score = vvs_data.get("vvs_score", 0)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_NAVY)
            pdf.cell(0, 7, f"VVS Score: {score:.1f} -- {verdict}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

        # Top 5 competitors table
        top_5 = competitors[:5]
        if top_5:
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*_NAVY)
            pdf.cell(0, 8, "Top 5 Competitors", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

            comp_headers = ["ASIN", "Title", "Price", "Rating", "Reviews"]
            comp_widths = [25, 85, 20, 18, 22]

            # Header
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_fill_color(*_NAVY)
            pdf.set_text_color(*_WHITE)
            for i, h in enumerate(comp_headers):
                pdf.cell(comp_widths[i], 7, h, border=1, align="C", fill=True)
            pdf.ln()

            # Data
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*_DARK)
            for ci, c in enumerate(top_5):
                if ci % 2 == 0:
                    pdf.set_fill_color(*_LIGHT_GRAY)
                else:
                    pdf.set_fill_color(*_WHITE)

                asin = c.get("asin", "")
                title = _safe_text(c.get("title", ""))
                if len(title) > 50:
                    title = title[:48] + ".."
                price = f"${c.get('price', 0):.2f}" if c.get("price") is not None else "-"
                rating = f"{c.get('rating', 0):.1f}" if c.get("rating") is not None else "-"
                reviews = str(c.get("review_count", 0))

                vals = [asin, title, price, rating, reviews]
                aligns = ["C", "L", "C", "C", "C"]
                for i, v in enumerate(vals):
                    pdf.cell(comp_widths[i], 6, v, border=1, align=aligns[i], fill=True)
                pdf.ln()


def _safe_text(text: str) -> str:
    """Strip characters that fpdf2 cannot encode in latin-1."""
    return text.encode("latin-1", errors="replace").decode("latin-1")
